### Get auth token
POST http://localhost:4111/api/v1/auth/login
Content-Type: Application/json

{
 "username":"nikol25",
 "password":"verysTRongPassword33$"
}

### Positive test: Create user by admin
POST http://localhost:4111/api/v1/admin/users
Content-Type: Application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
 "username":"nikol25",
 "password":"verysTRongPassword33$",
 "role":"USER"
}

### Negative test: Create user that already exists
POST http://localhost:4111/api/v1/admin/users
Content-Type: Application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
 "username":"nikol25",
 "password":"verysTRongPassword33$",
 "role":"USER"
}

### create account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic bmlrb2wyNTp2ZXJ5c1RSb25nUGFzc3dvcmQzMyQ=

### get customer account
GET http://localhost:4111/api/v1/customer/accounts
Content-Type: Application/json
Authorization: Basic bmlrb2wyNTp2ZXJ5c1RSb25nUGFzc3dvcmQzMyQ=